config/routes.rb
Sibyl::Engine.routes.draw do
  post "webhooks/:sibyl_event", to: "webhooks#webhook"

  resources :dashboard, only: [:index]

  resources :events do
    get :kinds, on: :collection
  end
end

app/models/sibyl/action.rb
module Sibyl
  class Action < Event
    OPERATORS = { gte: :>=, gt: :>, lte: :<=, lt: :<, eq: :== }.freeze

    # @param kind: String name of action (event is prepended with sibyl-action_)
    # @param user: String or Integer or object responding to `id`
    # @param with: (optional) extra data responding to `to_json`
    #                         preferably String or Integer
    # @param meta: (optional) extra meta info responding to `to_json`
    #                         preferably hash, e.g. page, UTM, etc.
    def self.record(kind, user:, with: nil, meta: {})
      user = user.id unless user.is_a?(Integer) || user.is_a?(String)
      Event.record("sibyl-action_#{kind}", user: user, with: with, meta: meta)
    end

    # @param kind can be a string or array of strings
    # @param user: String or Integer or object responding to `id`
    # @param with: (optional) extra data responding to `to_json`
    #                         preferably String or Integer
    # @param _times hash parameter wher key is operator and value is amount
    #               e.g. default is: `gte: 1`. Can be: gte gt eq lt lte
    # @returns: false if times condition not matched, actual count if matched
    def self.occurred?(kind, user:, with: nil, **times)
      kind = Array(kind).map { |k| "sibyl-action_#{k}" }
      kind = kind.first if kind.size == 1

      user = user.id unless user.is_a?(Integer) || user.is_a?(String)

      operator = (times.keys & OPERATORS.keys).first || :gte
      amount = times[operator] || 1

      rel = Event.where(kind: kind)
                 .where("data->'user' = '#{user.to_json}'")
      rel = rel.where("data->'with' = '#{with.to_json}'") if with

      size = rel.size
      size.send(OPERATORS[operator], amount) ? size : false
    end
  end
end

app/models/sibyl/trigger.rb
module Sibyl
  class Trigger # < ActiveRecord::Base
    def initialize(sibyl)
      @sibyl = sibyl
    end

    def self.trigger_map(trigs)
      Hash[trigs.map { |v| [v, self] }]
    end

    # Load the trigger class into the list of triggers
    def self.triggers(*trigs)
      trigger_map(trigs).each do |trigger, action|
        TRIGGERS[trigger] = Array(TRIGGERS[trigger]) << action
      end
    end

    protected

    def route_helpers
      Rails.application.routes.url_helpers
    end
  end
end

app/controllers/sibyl/application_controller.rb
module Sibyl
  class ApplicationController < ActionController::Base
    http_basic_authenticate_with(
      name: "sibyl",
      password: (ENV["SIBYL_PASSWORD"] || "12345678"),
      except: [:webhook]
    )

    private

    def to_csv(records)
      if records.is_a?(Hash)
        if records.key?(:funnel)
          "#{records[:funnel].first.keys.join(',')}\n#{records[:funnel].map { |v| v.values.join(',') }.join("\n")}"
        else
          "id,count\n#{records.map { |v| v.join(',') }.join("\n")}"
        end
      elsif records.is_a?(Numeric)
        "#{(params[:funnel][0] || params[:funnel][:"0"])[:operation]}\n#{records}"
      else
        "#{records.first.as_json.keys.join(',')}\n#{records.map do |r|
          (r.is_a?(Hash) ? r : r.serializable_hash).values.join(',')
        end.join("\n")}"
      end
    end

    def to_xml(records)
      if records.is_a?(Hash)
        records.to_xml
      elsif records.is_a?(Numeric)
        { (params[:funnel][0] || params[:funnel][:"0"])[:operation] => records }
      else
        records.to_xml
        # "#{records.first.as_json.keys.join(',')}\n#{records.map do |r|
        #   (r.is_a?(Hash) ? r : r.serializable_hash).values.join(',')
        # end.join("\n")}"
      end
    end
  end
end

app/controllers/sibyl/dashboard_controller.rb
require_dependency "sibyl/application_controller"
require "zlib"
require "json"

module Sibyl
  class DashboardController < ApplicationController
    def index
      @params = JSON.parse(Zlib.inflate(Base64.decode64(params[:zlib]))) rescue {}
      @panels = @params["panels"] || []
      # @panels = if params[:panels].is_a?(Hash)
                  # params[:panels].values
                # else
                  # params[:panels]
                # end
    end

    def show
    end
  end
end

app/controllers/sibyl/events_controller.rb
require_dependency "sibyl/application_controller"

module Sibyl
  class EventsController < ApplicationController
    before_action :set_event, only: [:show]

    def index
      @events = Event.all

      params_funnel = nil
      if params[:funnel]
        params_funnel = if params[:funnel].is_a?(Array)
                          params[:funnel].map(&:to_unsafe_h)
                        else
                          params[:funnel].to_unsafe_h
                        end
      end
      if params_funnel&.size&.> 1 # we are in a funnel!
        funnel = params_funnel.first
        funnel = funnel.last if funnel.is_a? Array

        from = previous = nil
        params_funnel&.each do |funnel|
          funnel = funnel.last if funnel.is_a? Array

          from = funnel[:from] if funnel[:from].present?
          funnel[:from] = from if funnel[:from].blank?
          previous = funnel[:previous] if funnel[:previous].present?
          funnel[:previous] = previous if funnel[:previous].blank?
        end

        if funnel[:group].blank? # dropoffs funnel
          # funnel_relation = Event.all.from("sibyl_events AS a0")
          funnel_relation = Event.all
          funnel_results = { funnel: [] }
          first_value = nil

          params_funnel&.each_with_index do |funnel, i|
            funnel = funnel.last if funnel.is_a? Array
            last_index = params_funnel.is_a?(Array) ? i - 1 : :"#{i - 1}"
            last_funnel = params_funnel[last_index]
            last_funnel = last_funnel.last if last_funnel.is_a? Array

            funnel_relation = Event.all.where_funnel(
              funnel[:property],
              last_funnel[:property],
              funnel_relation
            ) if i > 0
            funnel_relation = general_filters("a#{i}", funnel_relation, funnel)

            value = funnel_relation.operation(
              funnel[:operation],
              Event.property_query(funnel[:property]),
              funnel[:order]
            )
            first_value = value unless first_value
            percent = [(100.0 / first_value) * value, 100.0].min

            funnel_results[:funnel] << {
              value: value,
              percent: percent,
              label: funnel[:title].blank? ? funnel[:kind] : funnel[:title]
            }
          end

          @events = funnel_results
        else # multi calculation funnel
          params_funnel&.each_with_index do |funnel, i|
            funnel = funnel.last if funnel.is_a? Array

            # relation = Event.all.from("sibyl_events AS a#{i}")
            relation = Event.all
            relation = relation.from(
              "(#{funnel_relation.to_sql}) a#{i - 1}"
            ) if i > 0
            relation = general_filters("a#{i}", relation, funnel)
            if i.zero?
              funnel_relation = relation.operation(
                funnel[:operation],
                Event.property_query(funnel[:property]),
                funnel[:order],
                primitive: false
              )
            else
              funnel_relation = relation.operation(
                funnel[:operation],
                funnel[:group],
                funnel[:order],
                primitive: false
              )
            end
            funnel_relation = funnel_relation.group_by(
              "a#{i}",
              funnel[:group],
              funnel[:order]
            ) unless funnel[:group].blank? if i < params_funnel.size - 1

            if i == params_funnel.size - 1
              @events = funnel_relation.to_a[0][funnel[:operation]]
            end
          end
        end
      elsif params_funnel # just a single value query
        funnel = params_funnel
        funnel = funnel.is_a?(Hash) ? funnel[:"0"] : funnel[0]
        relation = Event.all

        relation = general_filters(relation, funnel)
        unless funnel[:group].blank?
          relation = relation.group_by(funnel[:group], funnel[:order])
        end
        relation = relation.operation(
          funnel[:operation],
          Event.property_query(funnel[:property]),
          funnel[:order]
        )
        @events = relation
      else
        relation = Event.all
        @events = general_filters(relation, {})
      end

      respond_to do |format|
        format.csv { send_data to_csv(@events) }
        format.json { render json: @events }
        format.xml { render xml: to_xml(@events) }
        format.html {}
      end
    end

    def kinds
      @kinds = Event.select(:kind).distinct.order(:kind)
    end

    def create
      @event = Event.new

      respond_to do |format|
        format.json do
          if @event.from_json(event_params).save
            render json: @event, status: :created # , location: @user
          else
            render json: @event.errors, status: :unprocessable_entity
          end
        end
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:type, :occurred_at, :data)
    end

    def time_from_seconds(seconds)
      Time.at(Time.now - Time.at(seconds)).to_s
    end

    def safe_limit(funnel)
      limit = funnel[:limit].blank? ? false : funnel[:limit].to_i
      if funnel[:operation].blank?
        limit || 50
      else
        limit
      end
    end

    def general_filters(as = nil, relation, funnel)
      relation = relation.in_kind(funnel[:kind])
      relation = relation.order_by(funnel[:order])

      funnel[:filters]&.each do |filter|
        filter = filter.last if filter.is_a? Array

        relation = relation.filter_property?(filter[:property])
        relation = relation.filter_property_value(
          filter[:filter], filter[:property], filter[:value]
        )

        if params[:format] == "csv" && !funnel[:operation]
          relation = relation.select(
            Sibyl::Event.columns.map(&:name).reject { |v| v == "data" } <<
              relation.property_query(filter[:property])
          )
        end
      end

      # ignore dates in later stages of a funnel
      # unless as && (m = as.match(/\w(\d+)/)) && m[1].to_i > 0
      relation = relation.date_from funnel[:from] unless funnel[:from].blank?
      relation = relation.date_to funnel[:to] unless funnel[:to].blank?
      relation = relation.date_previous funnel[:previous] unless funnel[:previous].blank?
      relation = relation.date_previous_to funnel[:previous_to] unless funnel[:previous_to].blank?
      # end

      limit = safe_limit(funnel)
      relation = relation.limit(limit) unless limit.blank?

      relation = relation.interval(funnel[:interval]) unless funnel[:interval].blank?

      relation
    end
  end
end

app/controllers/sibyl/webhooks_controller.rb
require_dependency "sibyl/application_controller"

module Sibyl
  class WebhooksController < ApplicationController
    def webhook
      if request.content_type.blank?
        data = JSON.parse(request.raw_post)
      else
        data = request.request_parameters[:webhook]
      end

      unless data.blank?
        Event.create_event "webhook_#{params[:sibyl_event]}", data
      end

      unless request.headers["X-Hook-Secret"].blank?
        response.headers["X-Hook-Secret"] = request.headers["X-Hook-Secret"]
      end

      head :ok, content_type: "text/html"
    end
  end
end

app/helpers/sibyl/application_helper.rb
module Sibyl
  module ApplicationHelper
  end
end

app/helpers/sibyl/dashboard_helper.rb
module Sibyl
  module DashboardHelper
  end
end

app/helpers/sibyl/events_helper.rb
module Sibyl
  module EventsHelper
    def hash_to_list(hash)
      content_tag(:ul) do
        html = ""
        hash.each_with_index do |kv, i|
          k, v = kv
          v = "{...}" if v.is_a? Hash
          html += content_tag(:li, "#{content_tag :i, k}: #{v}".html_safe)
          if i == 4 && hash.size > 5
            html += content_tag(:li, "...")
            break
          end
        end
        html.html_safe
      end.html_safe
    end

    def nested_hash_to_list(hash)
      content_tag(:ul) do
        html = ""
        hash.each do |k, v|
          v = nested_hash_to_list(v) if v.is_a? Hash
          html += content_tag(:li, "#{content_tag :i, k}: #{v}".html_safe)
        end
        html.html_safe
      end.html_safe
    end
  end
end

app/helpers/sibyl/webhooks_helper.rb
module Sibyl
  module WebhooksHelper
  end
end

app/views/sibyl/events/_filter_form.html.erb
<div class="container">
  <div class="row">
    <fieldset class="dropdown-item">
      <label><small>Event kind[s] (plain, comma, list)</small></label>
      <input class="form-control" type="text" name="funnel[][kind]" value="<%= params[:funnel]&.dig(0, :kind) %>" placeholder="(Event kind)">
    </fieldset>
  </div>
  <hr>
  <div class="filters-container">
    <% params[:funnel]&.dig(0, :filters)&.each_with_index do |_, i| %>
      <%= render "sibyl/events/filter_form_filter", i: i %>
    <% end %>
  </div>
  <button type="button" class="btn btn-primary btn-sm add-filter" onclick="$(this).parent().find('.filters-container').append('<%= escape_javascript(render partial: 'sibyl/events/filter_form_filter').gsub('"', "'") %>')">Add a filter</button>
  <hr>
  <div class="row">
    <fieldset class="dropdown-item col-sm-6">
      <label><small>Period from</small></label>
      <input class="form-control form-control-sm" type="text" name="funnel[][previous]" value="<%= params[:funnel]&.dig(0, :previous) %>" placeholder='(Period from)'>
    </fieldset>
    <fieldset class="dropdown-item col-sm-6">
      <label><small>to (5 days, 1minute, ...)</small></label>
      <input class="form-control form-control-sm" type="text" name="funnel[][previous_to]" value="<%= params[:funnel]&.dig(0, :previous_to) %>" placeholder='(Period to)'>
    </fieldset>
  </div>
  <div class="row">
    <fieldset class="dropdown-item col-sm-6">
      <label><small>Date from</small></label>
      <input class="form-control form-control-sm" type="text" name="funnel[][from]" value="<%= params[:funnel]&.dig(0, :from) %>" placeholder='(Date from)'>
    </fieldset>
    <fieldset class="dropdown-item col-sm-6">
      <label><small>to (yyyy-mm-dd)</small></label>
      <input class="form-control form-control-sm" type="text" name="funnel[][to]" value="<%= params[:funnel]&.dig(0, :to) %>" placeholder='(Date to)'>
    </fieldset>
  </div>
  <div class="row">
    <fieldset class="dropdown-item col-sm-6">
      <label><small>Limit (number)</small></label>
      <input class="form-control form-control-sm" type="text" name="funnel[][limit]" value="<%= params[:funnel]&.dig(0, :limit) %>" placeholder='(Limit results)'>
    </fieldset>
    <fieldset class="dropdown-item col-sm-6">
      <label><small>Order by</small></label><br>
      <%= select_tag "funnel[][order]", options_for_select({ Newest: "desc", Oldest: "asc" }, params[:funnel]&.dig(0, :order)), class: "form-control form-control-sm c-select" %>
    </fieldset>
  </div>
</div>

app/views/sibyl/events/_filter_form_filter.html.erb
<% i ||= 0 %>
<div class="filter-wrapper">
  <div class="row">
    <fieldset class="dropdown-item pull-xs-left">
      <label><small>Property (plain, comma, list)</small></label>
      <div class="input-group">
        <input class="form-control form-control-sm" type="text" name="funnel[][filters][][property]" value="<%= params[:funnel]&.dig(0, :filters, i, :property) %>" placeholder="(Property target)">
        <div class="input-group-btn">
          <button type="button" class="btn btn-danger btn-sm" onclick="removeFilter(event, $(this)); return false">x</button>
        </div>
      </div>
    </fieldset>
  </div>
  <div class="row">
    <fieldset class="dropdown-item">
      <label><small>Filter | Value ("string" / number)</small></label>
      <div class="input-group">
        <div class="input-group-btn">
          <%= select_tag "funnel[][filters][][filter]", options_for_select({ "Equal to": "eq", "Not eql": "ne", "Greater": "gt", "Grtr or eql": "gte", "Less": "lt", "Less or eql": "lte", "Like": "like", "Not like": "not_like", "Blank": "blank", "Not blank": "not_blank", "Contains": "contains", "Contained in": "contained", "Has key": "one_key", "Any keys": "any_keys", "All keys": "all_keys" }, params[:funnel]&.dig(0, :filters, i, :filter)), class: "form-control form-control-sm c-select" %>
        </div>
        <input class="form-control form-control-sm" type="text" name="funnel[][filters][][value]" value="<%= params[:funnel]&.dig(0, :filters, i, :value) %>" placeholder='(Filter property value)'>
      </div>
    </fieldset>
  </div>
  <hr>
</div>

app/views/sibyl/events/index.html.erb
<% content_for :navbar_right do %>
  <div class="nav-item dropdown">
    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Filter</a>
    <div class="dropdown-menu dropdown-menu-right" style="min-width: 420px">
      <form action="" class="form">
        <%= render "sibyl/events/filter_form" %>
        <div class="dropdown-divider"></div>
        <fieldset class="form-group">
          <button type="submit" class="btn btn-success btn-sm pull-xs-right m-x-1">Go!</button>
        </fieldset>
      </form>
    </div>
  </div>
<% end %>

<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1 class="pull-sm-left">Listing Events</h1>
  <%= link_to "Export CSV", events_path(format: "csv", params: params.except(:action, :controller).to_unsafe_h), class: "pull-sm-right" %><br>
  <%= link_to "Event Kinds", kinds_events_path, class: "pull-sm-right" %>

  <table class="table">
    <thead>
      <tr>
        <th>Kind</th>
        <th>Occurred at</th>
        <th>Data</th>
        <th>Created at</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.kind %></td>
          <td><%= event.occurred_at %></td>
          <td><%= hash_to_list event.data %></td>
          <td><%= event.created_at %></td>
          <td><%= link_to 'Show', event, class: "btn btn-primary-outline btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sibyl/events/kinds.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1 class="pull-sm-left">All Event Kinds</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Kind</th>
      </tr>
    </thead>

    <tbody>
      <% @kinds.each do |kind| %>
        <tr>
          <td><%= kind.kind %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sibyl/events/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h2>
    <%= @event.kind %>
  </h2>

  <p>
    <strong>Occurred at:</strong>
    <%= @event.occurred_at %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= nested_hash_to_list @event.data %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= @event.created_at %>
  </p>
</div>